<?php


$andamentos = array(

// 0
'0_URL' => 'http://www.direito2010.com.br',
'0_language' => 'Português do Brasil [br]',
'0_list' => 'fabio@direito2010.com.br',
'0_maintainer' => 'Fábio Torres (fabio@direito2010.com.br)',


// A
'add_adverso_s' => 'Adicionar adverso',
'add_clienteanisation_s' => 'Adicionar cliente',
'add_user_case' => 'Adicionar colaborador',
'app_button_edit' => ' Editar',
'app_button_cumprir' => ' Cumprir',
'app_button_new' => ' Digite uma nova atividade',
'app_info_delete' => 'Excluir atividade.',
'app_info_cumprir' => 'Crumprir atividade.',
'app_info_is_deleted' => 'Esta atividade foi excluída.',
'app_info_is_deleted2' => 'Para anular a eliminação, editar a atividade, em seguida, desmarque a caixa excluir.',
'app_info_see_cal_for_day_tooltip' => ' Ir para a página do calendário deste dia.',
'app_input_authors' => ' Usuários participantes:',
'app_input_adversos' => ' Adversos participantes',
'app_input_perf_desc' => ' Descrição do cumprimento',
'app_input_created_by' => ' Criado por',
'app_input_description' => ' Descrição',
'app_input_for_case' => ' Nomear um processo:',
'app_input_involving_adversos' => ' Envolvendo:',
'app_input_related_to_case' => ' Referente ao processo:',
'app_input_reminder' => ' Lembrete:',
'app_input_reminder_offset' => ' Lembre-me:',
'app_input_reminder_time' => ' Lembra-me a:',
'app_input_time_length' => ' Tempo gasto na atividade:',
'app_input_title' => ' Título:',
'app_input_type' => ' Tipo:',
'archives_button_new' => ' Novo backup:',
'archives_info_how_to_download' => ' Os backups podem ser baixados diretamente ou através de FTP / SSH ou ainda ser excluído, clicando no ícone da lixeira.',
'archives_info_how_to_upload' => ' Para carregar um backup, digite o nome do arquivo para upload, em seguida, clique no botão salvar.',
'archives_info_new_success' => ' O backup do banco de dados foi criado com sucesso e salvas como @name@.',
'archives_info_no_previous' => ' Não há backups feitos anteriormente.',
'archives_info_option_restore' => ' Retornar o banco de dados para o estado exato no momento do backup.',
'archives_info_restore_will_delete' => ' A fim de restaurar o backup do arquivo, banco de dados atual será excluída. Continuar?',
'archives_info_what_is_backup' => ' Backups permitir que as informações no banco de dados do sistema a ser exportados para um arquivo separado. Em caso de emergência, este arquivo pode ser usado para recuperar as informações do sistema. Para criar o backup, clique no botão abaixo.',
'archives_input_option_restore' => ' Restaurar',
'archives_input_option_sync' => ' Sincronize',
'archives_input_select_backup' => ' Selecione backup para restaurar:',
'archives_subtitle_new' => ' Criar um novo backup',
'archives_subtitle_previously_made' => ' Anteriormente fez backups',
'archives_subtitle_restore' => ' Restaurar um backup',
'archives_subtitle_upload' => ' Fazer upload de um backup',
'archives_tab_all_cases' => ' Todos os Processos',
'archives_tab_export' => ' Backup',
'archives_tab_import' => ' Restaurar',
'author_subtitle_appointments' => ' Futuras atividades ou tarefas para @author@.',
'author_subtitle_appointments_app' => 'Lista geral dos compromissos',
'author_subtitle_cases' => ' Processos que envolvam @author@',
'author_subtitle_followups' => ' Últimos andamentos por @author@',
'author_subtitle_reports' => ' Relatórios de atividade para @author@',
'authorconf_button_change_password' => 'Mudança de senha',
'authorconf_button_update_preferences' => 'Salvar como preferências',
'authorconf_input_font_size' => 'Tamanho do Texto:',
'authorconf_input_language' => 'Lingua:',
'authorconf_input_large_font' => 'Grande',
'authorconf_input_medium_font' => 'Médio',
'authorconf_input_mode' => 'Modo de IU:',
'authorconf_input_mode_extended' => 'Extendido',
'authorconf_input_mode_simple' => 'Simples',
'authorconf_input_password' => 'Senha:',
'authorconf_input_password_confirm' => 'Confirmar nova senha:',
'authorconf_input_password_current' => 'Senha atual:',
'authorconf_input_password_new' => 'Nova senha:',
'authorconf_input_results_per_page' => 'Resultados por página:',
'authorconf_input_screen' => 'Mostrar:',
'authorconf_input_screen_narrow' => 'Pequeno',
'authorconf_input_screen_wide' => 'Grande',
'authorconf_input_small_font' => 'Pequeno',
'authorconf_input_theme' => 'Cor da Interface:',
'authorconf_input_theme_blue' => 'Azul', 
'authorconf_input_theme_green' => 'Verde',
'authorconf_input_theme_monochrome' => 'Monochromatica',
'authorconf_input_theme_orange' => 'Laranja',
'authorconf_input_time_interval_absolute' => ' Absoluto (horário de início - o tempo final)',
'authorconf_input_time_interval_relative' => ' Relativa (início + tempo de duração)',
'authorconf_input_time_intervals_notation' => ' Tempo de notação intervalos',
'authorconf_input_time_intervals_notation_floatdays_hours_minutes' => ' Em dias, horas e minutos (campos separados para cada valor)',
'authorconf_input_time_intervals_notation_hours_only' => ' Em apenas algumas horas (ex: 5 = 5 horas, ou 0.2 = 12 minutos)',
'authorconf_input_ui_time' => ' Entrada método de intervalos de tempo',
'authorconf_subtitle_advanced' => ' Características avançadas',
'authorconf_subtitle_interface' => 'Interface',
'authorconf_subtitle_password' => 'Mudar senha:',
'authorconf_tab_advanced' => ' Advanced',
'authorconf_tab_interface' => ' Interface',
'authoredit_button_edit' => ' Editar informações do usuário',
'authoredit_button_new' => ' Criar um novo usuário',
'authoredit_input_id' => ' User ID:',
'authoredit_input_status' => ' Status:',
'authoredit_input_status_admin' => ' Administrator',
'authoredit_input_status_manager' => ' Gestor',
'authoredit_input_status_external' => ' Externas',
'authoredit_input_status_normal' => ' Normal',
'authoredit_input_status_trash' => ' Fechado',
'authoredit_input_status_waiting' => ' Esperando para registrar',
'authoredit_input_username' => 'Nome de usuário',
'authoredit_subtitle_connectionidentifiers' => ' Identificadores de conexão do sistema',
'authoredit_subtitle_personalinfo' => 'Informação Pessoal',
'appointments04' => 'Prazo',

// B

'button_delete' => ' Delete', 
'button_next' => 'Próximo',
'button_reload_page' => 'Atualizar',
'button_search' => 'Buscar',
'button_filter' => ' Filtrar',
'button_reset' => ' Limpar',
'button_validate' => 'Validar',
'button_zoom' => ' Zoom',

// C
'calendar_button_afternoon' => ' Tarde (p.m.)',
'calendar_button_daily' => ' Calendário diário', 
'calendar_button_fullday' => ' Dia inteiro',
'calendar_button_monthly' => ' Calendário mensal',
'calendar_button_morning' => ' Manhã (a.m.)',
'calendar_button_nextapps' => ' próximas atividades',
'calendar_button_now' => ' Hoje',
'calendar_button_weekly' => ' Calendário semanal',
'calendar_info_date' => 'Data',
'calendar_info_noacts' => ' Não há atividades.',
'case_ac_input_rights' => ' O direito de acesso:',
'case_button_add_adverso' => ' Adicione um adverso',
'case_button_add_cliente' => ' Adicionar um cliente',
'case_button_new' => ' Novo Processo',
'case_filter_owner_option_all' => ' Todos os Processos',
'case_filter_owner_option_my' => ' Meus acompanhamentos',
'case_filter_owner_option_public' => ' Processos Públicos',
'case_filter_period_option_m1' => ' No mês passado',
'case_filter_period_option_m3' => ' Nos últimos 3 meses',
'case_filter_period_option_m6' => ' Nos últimos 6 meses',
'case_filter_period_option_w1' => ' Na semana passada',
'case_filter_period_option_y1' => ' No ano passado',
'case_filter_period_option_year' => ' ano @year@',
'case_info_author_assigned' => ' @name@: O usuário foi designado para o processo.',
'case_info_author_unassigned' => ' @name@: O usuário foi removido do processo.',
'case_info_adverso_emptylist' => ' Não há adversos associados a este processo.',
'case_info_delete_adverso' => ' Remover este adverso a partir deste processo.',
'case_info_delete_cliente' => ' Remover este cliente deste processo.',
'case_input_comarca' => 'Comarca: ',
'case_input_state' => 'Estado:',
'case_input_vara' => 'Vara:',
'case_input_author' => 'Usuário:',
'case_input_authors' => 'Usuários:',
'case_input_adversos' => 'Adversos:',
'case_input_cliente' => 'Cliente:',
'case_input_collaboration' => ' <b>Controle de acesso:</b>',
'case_input_collaboration_read' => ' Usuários podem consultar.',
'case_input_collaboration_write' => ' Usuários podem contribuir.',
'case_input_court_archive' => 'Nº do Processo:',
'case_input_date_assigned' => 'Data da inclusão:',
'case_input_date_conclusion' => ' Data de conclusão:',
'case_input_date_creation' => 'Data da criação:',
'case_input_date_updated' => 'Data da movimentação',
'case_input_id' => 'Nº da Pasta:',
'case_input_legal_reason' => 'Tipo de ação:',
'case_input_p_cliente' => 'Cliente:',
'case_input_autor' => 'Autor do Processo:',
'case_input_reu' => 'Réu do Processo:',
'case_input_notes' => ' Objeto:',
'case_input_causa' => ' Valor da causa:',
'case_input_option_ac_admin' => ' Processo do administrador',
'case_input_option_ac_read' => ' Consultar informações sobre o processo',
'case_input_option_ac_remove' => ' Un-atribuir a partir do processo',
'case_input_option_ac_write' => ' Adicionar informações ao processo',
'case_input_clienteanisations' => 'Clientes:',
'case_input_stage' => ' Fase do processo:',
'case_input_status' => 'Status do processo:',
'case_input_status_id' => 'Status',
'case_input_processo' => 'Número do processo:',
'case_input_processo_vara' => 'Processo/Vara',
'case_input_p_adverso' => 'Adverso',
'case_input_title' => 'Adverso',
'case_input_comar' => 'Comarca',
'case_input_total_time' => ' Tempo gasto:',
'case_status_option_open' => ' Ativo',
'case_status_option_closed' => ' Inativo',
'case_status_option_deleted' => ' Extinto',
'case_status_option_suspended' => ' Suspenso',
'case_status_option_draft' => ' Rascunho',
'case_status_option_merged' => ' Outros',
'case_subtitle_appointments' => ' Futuros compromissos ou prazos para este processo',
'case_subtitle_attachments' => ' Documentos complementares relacionados ao processo',
'case_subtitle_adversos' => 'Partes',
'case_subtitle_followups' => 'Movimentação do processo',
'case_subtitle_general' => 'Informação Geral do Processo',
'case_subtitle_recent_followups' => ' Andamentos Recentes',
'case_subtitle_times' => ' O tempo total gasto no processo',
'case_subtitle_times_by_agenda' => ' Tempo gasto em outras tarefas administrativas',
'case_subtitle_times_by_case' => ' Tempo gasto por processo',
'case_subtitle_times_by_fu' => ' Tempo gasto por processo de tipos de andamento',
'case_tooltip_view_access_rights' => ' Ver no processo os direitos de acesso para @author@.',
'case_tooltip_view_author_details' => ' Ver os detalhes do @author@.',
'adverso_button_add_cliente' => ' Associado a um cliente',
'adverso_button_edit' => ' Editar',
'adverso_button_send' => ' Enviar',
'adverso_button_new' => ' Novo Adverso',
'adverso_button_export' => ' Exportar',
'adverso_button_sendmail' => ' Enviar',
'adverso_button_new_for_case' => ' Registrar um novo adverso e anexar a este processo',
'adverso_info_created_attached' => ' O adverso foi registrado e anexado ao processo:',
'adverso_info_delete_cliente' => ' Excluir a relação adverso-cliente.',
'adverso_input_id' => 'Pasta:',
'adverso_input_notes' => ' Observação:',
'adverso_subtitle_associated_cliente' => '<MODIF>Relação com cliente',
'adverso_subtitle_attachments' => ' Anexos',
'adverso_subtitle_cases' => ' Processos envolvendo este adverso',
'adverso_subtitle_contacts' => ' Contatos',
'adverso_subtitle_clienteanisations' => ' Organizações',
'adverso_subtitle_view_general' => 'Informação Geral',
'currency_default_format' => 'R$',
'currency_format_placement' => ' @currency@@money@',
'currency_format_seperator_cents' => ' .',
'currency_format_seperator_hundreds' => ' ,',
'count' => 'Contagem',
'court_session' => 'Compromisso',


// D
'date_day_1' => '01 de',
'date_day_10' => '10 de',
'date_day_11' => '11 de',
'date_day_12' => '12 de',
'date_day_13' => '13 de',
'date_day_14' => '14 de',
'date_day_15' => '15 de',
'date_day_16' => '16 de',
'date_day_17' => '17 de',
'date_day_18' => '18 de',
'date_day_19' => '19 de',
'date_day_2' => '02 de',
'date_day_20' => '20 de',
'date_day_21' => '21 de',
'date_day_22' => '22 de',
'date_day_23' => '23 de',
'date_day_24' => '24 de',
'date_day_25' => '25 de',
'date_day_26' => '26 de',
'date_day_27' => '27 de',
'date_day_28' => '28 de',
'date_day_29' => '29 de',
'date_day_3' => '03 de',
'date_day_30' => '30 de',
'date_day_31' => '31 d',
'date_day_4' => '04 de',
'date_day_5' => '05 de',
'date_day_6' => '06 de',
'date_day_7' => '07 de',
'date_day_8' => '08 de',
'date_day_9' => '09 de',
'date_format_full' => '@day_name@, @day_order@ @month_name@ @year@, @hours@H@mins@',
'date_format_short' => '@day@ @month_short@ @year@, @hours@h@mins@',
'date_month_1' => 'Janeiro',
'date_month_10' => 'Outubro',
'date_month_11' => 'Novembro',
'date_month_12' => 'Dezembro',
'date_month_2' => 'Fevereiro',
'date_month_3' => 'Março',
'date_month_4' => 'Abril',
'date_month_5' => 'Maio',
'date_month_6' => 'Junho',
'date_month_7' => 'Julho',
'date_month_8' => 'Agosto',
'date_month_9' => 'Setembro',
'date_month_short_1' => 'Jan',
'date_month_short_10' => 'Out',
'date_month_short_11' => 'Nov',
'date_month_short_12' => 'Dez',
'date_month_short_2' => 'Fev',
'date_month_short_3' => 'Mar',
'date_month_short_4' => 'Abr',
'date_month_short_5' => 'Mai',
'date_month_short_6' => 'Jun',
'date_month_short_7' => 'Jul',
'date_month_short_8' => 'Ago',
'date_month_short_9' => 'Set',
'date_wday_0' => 'Domingo',
'date_wday_1' => 'Segunda',
'date_wday_2' => 'Terça',
'date_wday_3' => 'Quarta',
'date_wday_4' => 'Quinta',
'date_wday_5' => 'Sexta',
'date_wday_6' => 'Sábado',
'date_wday_7' => 'Domingo',
'date_wday_short_0' => 'Do',
'date_wday_short_1' => 'Se',
'date_wday_short_2' => 'Te',
'date_wday_short_3' => 'Qu',
'date_wday_short_4' => 'Qu',
'date_wday_short_5' => 'Se',
'date_wday_short_6' => 'Sá',
'date_wday_short_7' => 'Do',
'directories_bad_rights' => 'neste diretório você não tem permissão para editar:',
'directories_bad_rights_cause' => 'Para mudanças, utilize o seu adverso SSH/SFTP para ordenar as permissões de acesso para cada diretório. O procedimento é detalhado no guia de instalação.',
'directories_continue' => 'Uma vez lido, você poderá atualizar esta página.',
'directories_missing' => 'Os seguintes diretórios não foram encontrados',
'directories_missing_possible_cause' => 'A possível causa é um erro de digitação de letras maisculas e minusculas. Por favor tenha certeza que a escrita confere com os diretórios apresentados abaixo; Se incorretos, renomeie os diretórios utilizando seu adverso SSH/SFTP corrigindo o erro.',
'directories_setup_problem' => 'Problema nas permissões de acesso',
'directories_setup_start' => 'Preliminar: Configurar as permissões de acesso',

// E
'edit' => 'Editar',
'edit_case_information' => 'Editar as informações do processo',
'error_add_auth_no_rights' => 'Você não tem permissão para acessar os direitos sobre este processo!',
'error_no_case_specified' => 'O nome do processo não foi especificado',
'error_no_edit_permission' => 'Você não tem permissão para editar este processo!',
'error_no_read_permission' => 'Você não tem permissão para ver este processo!',
'expense_button_comment' => ' Adicionar um comentário',
'expense_button_edit' => ' pedido Editar',
'expense_button_new' => ' Novo pedido',
'expense_filter_owner_option_all' => ' Todos as despesas',
'expense_filter_owner_option_my' => ' Minhas despesas',
'expense_filter_owner_option_public' => ' Despesas públicas',
'expense_input_comment' => ' Comentário:',
'expense_input_case' => 'Pasta',
'expense_input_user' => 'Usuário',
'expense_input_comments' => 'Comentários',
'expense_input_cost' => ' Custo:',
'expense_input_description' => ' Descrição:',
'expense_input_id' => ' Identidade da Solicitação:',
'expense_input_status' => ' Estado:',
'expense_input_type' => ' Tipo:',
'expense_status_option_deleted' => ' excluída',
'expense_status_option_granted' => ' concedido',
'expense_status_option_pending' => ' pendente',
'expense_status_option_refused' => ' recusou-se',
'expenses_subtitle_comment' => ' Comentário',
'expenses_subtitle_comments' => ' Comentários',
'export_button_case' => ' Exportar informações sobre o processo',
'export_button_adverso' => ' Exportar informações do adverso',
'export_button_followup' => ' Exportar informações de andamento',
'export_button_cliente' => ' Exportar informações da cliente',

// F
'file_info_delete' => ' Excluir este documento.',
'file_info_emptylist' => ' Não existem documentos anexados.',
'file_input_description' => ' Descrição:',
'file_input_name' => ' Nome do arquivo:',
'file_input_size' => ' Tamanho:',
'file_input_type' => ' Tipo:',
'file_size_info_bytes' => ' @size@ b',
'file_size_info_gbytes' => ' @size@ Gb',
'file_size_info_kbytes' => ' @size@ Kb',
'file_size_info_mbytes' => ' @size@ Mb',
'format_date_full' => '@day_name@, @day_order@ @month_name@ @year@',
'format_date_short' => '@day@ @month_short@ @year@',
'format_datetime_full' => '@day_name@, @day_order@ @month_name@ @year@, @hours@h@mins@',
'format_datetime_short' => '@day@ @month_short@ @year@, @hours@h@mins@',
'format_time_short' => '@hours@:@mins@',
'fu_button_desc_less' => ' Mostrar só o começo das descrições.',
'fu_button_desc_more' => ' Mostrar o texto completo das descrições.',
'fu_button_edit' => ' Editar seguimento',
'fu_button_stats_less' => ' Ocultar as estatísticas detalhadas.',
'fu_button_stats_more' => ' as estatísticas mais detalhadas.',
'fu_info_add_future_activity' => ' Agende um compromisso futuro para o processo.',
'fu_info_after_event' => ' Em relação com o evento “@title@” em @date@, envolvendo @participants@ ...',
'fu_info_delete' => ' Excluir este seguimento.',
'fu_info_emptydesc' => ' Nenhuma descrição.',
'fu_info_is_deleted' => ' Este andamento é eliminado.',
'fu_info_is_deleted2' => ' Para cancelar a exclusão, editar o seguimento, em seguida, desmarque a caixa excluir.',
'fu_input_child_appointment' => ' Agendado para:',
'fu_input_stopday' => 'Dp',
'fu_input_stopday_text' => 'Igual ou maior que',
'fu_input_last_text' => 'Último',
'fu_input_conclusion' => ' Encerramento:',
'fu_input_current_stage' => ' Fase atual:',
'fu_input_current_status' => ' Andamento:',
'fu_input_date_end' => 'Fim:',
'fu_input_date_start' => 'Começo:',
'fu_input_description' => 'Descrição:',
'fu_input_for_case' => ' Processo n.:',
'fu_input_id' => ' Id do seguimento:',
'fu_input_involving_adversos' => ' Envolvendo:',
'fu_input_next_stage' => ' Próxima etapa:',
'fu_input_parent_appointment' => ' Relacionado ao:',
'fu_input_sentence' => ' Condenação:',
'fu_input_sum_billed' => 'Valor:',
'fu_input_time_length' => ' O tempo gasto na atividade:',
'fu_input_type' => 'Andamento:',

// G
'generic_info_delete_contact' => ' Remover este contato.',
'generic_input_contact_other' => ' Outros Contatos:',
'generic_input_total' => ' Total:',
'generic_subtitle_contacts' => ' Contatos',
'generic_subtitle_document_add' => ' Adicionar um novo documento',
'generic_subtitle_general' => ' Informações Gerais',
'generic_subtitle_warning' => ' Aviso!',
'generic_tab_agenda' => ' Agenda',

'generic_tab_agenda_geral' => ' Agenda Geral',
'generic_tab_agenda_served' => ' Agenda Cumprida',
'generic_tab_agenda_pending' => ' Agenda Pendente',

'generic_tab_cases' => ' Processos',
'generic_tab_adversos' => ' Adversos',
'generic_tab_documents' => ' Documentos',
'generic_tab_followups' => ' Andamentos',
'generic_tab_general' => ' Cadastro',
'generic_tab_cliente' => ' Organizações',
'generic_tab_reports' => ' Atividades',
'generic_tab_representatives' => ' Representantes',


// H
'help_intro_archive_create' => ' Você pode criar arquivos de backup do banco de dados usando o botão abaixo. Você também pode baixar.',
'help_intro_archive_restore' => ' Você pode restaurar ou sincronizar o sistema, utilizando o formulário abaixo. O processo é dividido em duas etapas. A primeira forma permite que você armazene um arquivo no sistema. A segunda forma permite que você selecione um arquivo para restaurar ou sincronizar o sistema.',
'help_intro_author_list' => ' Lista de todos os usuários cadastrados no sistema. Você pode clicar sobre o nome do usuário para exibir seus detalhes. Se você for um administrador, você pode criar novos usuários usando o botão abaixo.',
'help_intro_case_ac' => ' Cada usuário designado para o processo pode ter um nível de acesso específico para o processo. Por exemplo, um usuário pode ter o direito de consultar (ler), a contribuir (escrever), para corrigir (editar) ou para administrar o processo (fase de mudança do processo / status, adicionar / remover outros usuários para o processo, etc). Você também pode atribuir um usuário a partir de um processo de aqui.',
'help_intro_case_list' => ' Lista dos Processos que você está trabalhando. Você pode clicar sobre o título do caso na lista abaixo para visualizar a página de detalhes do processo escolhido. Você também pode limitar a lista de Processos com critérios específicos, usando os filtros.',
'help_intro_adverso_list' => ' Lista de todos os adversos cadastrados no sistema. Você pode clicar sobre o nome do adverso para ver seus detalhes. Você pode também registrar um novo adverso usando o botão abaixo.',
'help_intro_expenses_list' => ' Lista de pedidos internos, como solicitações para cobrir as despesas relacionadas a um processo, que estão esperando a aprovação dos administradores do escritório, ou foram recentemente aprovados. Você pode clicar sobre a descrição gasto na lista abaixo para ver mais informações sobre ele.',
'help_intro_keyword_list' => ' Um certo número de campos podem ser personalizados ao seu ambiente. Eles normalmente são relacionados à informação estatística e, portanto, oferecem uma gama limitada de opções. O sistema "campos são usados em funções do sistema, tais como os tipos de segmentos ou pedidos internos. O usuário "campos pode ser usada para adicionar novos domínios estatísticos para certos elementos, como os processos, os adversos ou empresas. Outros campos podem ser adicionados ou removidos da configuração do site "política" na página.',
'help_intro_cliente_list' => ' Lista de todas as empresas registadas no sistema. Você pode clicar sobre o nome do cliente para ver seus detalhes. Você também pode registrar uma novo cliente usando o botão abaixo.',
'help_title_about' => ' Sobre ...',
'help_title_about_contrib' => ' Contribuintes',
'help_title_about_license' => ' Licença e os termos de uso',
'help_title_archives' => ' Arquivo',
'help_title_archives_export' => ' Exportar arquivos',
'help_title_archives_import' => ' Importar arquivos',
'help_title_archives_intro' => ' Introdução',
'help_title_authors' => ' Usuários',
'help_title_authors_admin' => ' Papel dos administradores',
'help_title_authors_edit' => ' A gestão de utilizadores',
'help_title_authors_intro' => ' Introdução',
'help_title_cases' => ' Processos',
'help_title_cases_followups' => ' Processo para acompanhar',
'help_title_cases_intro' => ' Introdução',
'help_title_cases_participants' => ' participantes do processo',
'help_title_cases_statusstage' => ' Novo caso de estágio ou estado',
'help_title_adversos' => ' Adversos',
'help_title_adversos_intro' => ' Introdução',
'help_title_adversos_newadverso' => ' Registro de adversos',
'help_title_adversos_newcliente' => ' O registro dos clientes',
'help_title_adversos_cliente' => ' Ligando os adversos e as empresas',
'help_title_help' => ' Ajuda Legal Processo de Gestão',
'help_title_install_database' => ' O banco de dados SQL conexão',
'help_title_install_permissions' => ' Configurando permissões de diretório',
'help_title_install_personal' => ' As informações pessoais',
'help_title_installation' => ' Instalação',
'help_title_keywords' => ' Campos',
'help_title_keywords_intro' => ' Introdução',
'help_title_keywords_new' => ' Criando um novo campo item',
'help_title_keywords_new_group' => ' Criar um grupo novo campo',
'help_title_keywords_remove' => ' Removendo um item de um campo',
'help_title_reports' => ' Relatórios',
'help_title_reports_edit' => ' Personalizando um relatório',
'help_title_reports_intro' => ' Introdução',
'help_title_siteconfig' => ' configurações do sistema',
'help_title_siteconfig_collab' => ' O trabalho colaborativo',
'help_title_siteconfig_general' => ' Informações gerais',
'help_title_siteconfig_policy' => ' Política de escritório',
'help_title_siteconfig_regional' => ' As definições regionais',
'help_title_tools' => ' Ferramentas',
'help_title_tools_agenda' => ' Agenda',
'help_title_tools_documents' => ' Documentos',
'help_warning_no_files' => ' Os arquivos de ajuda não são instalados.',
'help_warning_no_section' => ' A seção de ajuda solicitada não existe.',


// I
'info_free_software' => 'Desenvolvido por Fábio Torres.',
'info_free_software1' => 'distribuido',
'info_free_software2' => 'licença GPL',
'info_impot_dados' => 'Somente os dados de backup não existentes no banco de dados serão importados. Isto é útil para importar os dados perdidos desde o último backup, sem alterar as informações existentes. Aviso: Esta operação pode quebrar a integridade de dados, especialmente se a importação de dados entre instalações diferentes.',
'info_greetings' => 'Bom Dia',
'info_more_than_five' => '(Mais de 5 letras)',
'info_more_than_three' => '(Mais de 3 letras)',
'info_no' => 'não',
'info_not_available' => 'Selecione',
'info_or' => 'ou',
'info_password_confirm' => '(Digite sua senha mais uma vez para evitar erros)',
'info_technical_problem_database' => 'A conexão ao banco de dados falhou. É possível que ele não esteja rodando ou o login e a senha foram rejeitados. Por favor consulte a mensagem disponível abaixo (if any) para mais informações.',
'info_upgrade_database1' => ' A estrutura do banco de dados foi alterada. Para poder usar a nova versão do software, a estrutura de banco de dados será atualizada.',
'info_upgrade_database2' => ' Para prosseguir com a atualização automática, clique aqui.',
'info_upgrade_database3' => ' A atualização do banco de dados foi um sucesso.',
'info_upgrade_database5' => ' Clique aqui para voltar à página principal.',
'info_yes' => 'sim',
'info_yes_mandatory' => '<MODIF>sim (obrigatório)',
'info_yes_optional' => '<MODIF>sim (opcional)',
'info_your_contact_information' => 'Suas informações para contato ...',
'input_connection_identifiers' => 'Suas identificações de conexão ...',
'input_email' => 'Endereço de E-mail:',
'input_filter_case_comar' => ' Comarca',
'input_filter_case_vara' => ' Vara',
'input_filter_case_condicao' => ' Condição do Adverso',
'input_filter_case_state' => ' UF',
'input_filter_case_owner' => ' Permissão',
'input_filter_case_pasta' => ' Número da Pasta',
'input_filter_case_processo' => ' Número do processo',
'input_filter_case_parte' => ' Parte adversa',
'input_filter_case_status' => ' Status',
'input_filter_case_time' => 'Tempo',
'input_filter_case_type' => 'Andamento',
'input_filter_cliente_name' => 'Clientes',
'input_filter_case_title' => 'Filtro de processos',
'input_filter_list_title' => 'Lista de processos',
'input_search_author' => ' Encontrar usuário',
'input_search_case' => 'Localizar Processo',
'input_search_adverso' => 'Adverso:',
'input_search_exp' => ' Encontre um pedido:',
'input_search_cliente' => 'Cliente:',
'input_search_clienteanisation' => 'Procurar cliente:',
'input_search_rep' => ' Encontre o relatório:',
'install_connection_login' => 'Conexão do login',
'install_connection_password' => 'Conexão da senha',
'install_connection_succeeded' => 'Conexão realizada.',
'install_create_new_database' => 'Criar um novo banco de dados',
'install_database_address' => 'Endereço do banco de Dados',
'install_database_install_failed' => 'Volte para página alterior, selecione outro banco de dados ou crie um novo. Verique a informação disponibilizada por seu provedor de hospedagem.',
'install_database_installed_ok' => 'Banco de dados pronto para uso.',
'install_enter_name_manually' => ' Você sabe o nome exato do banco de dados...',
'install_info_application_ready' => 'O sistema pronto para uso',
'install_info_do_not_fclienteet' => 'Não esqueça seus códigos de acesso!',
'install_info_go_back_verify_data' => 'Volte para página anterior, e verifique a informação disponibilizada.',
'install_info_more_about_software' => ' Para obter mais informações sobre o software, tais como os anúncios recentes de documentação, sobre como estender o software, etc, visite@url@. Para solicitar os recursos, reportar defeito ou qualquer outro comentário, escreva para legalcase-devel@lists.sf.net. Sua opinião é muito importante para nos ajudar a melhorar a qualidade do software.',
'install_info_new_account_1' => 'O sistema prividenciará um acesso padrão ao site.',
'install_info_sql_connection' => 'Referese a informação disponibilizada a você pelo seu administrador do sistema: se seu servidor suportar SQL, ele deve dar a você os códigos de acesso ao servidor SQL.',
'install_info_sql_connection_failed' => '<b>N.B.</b> Em vários servidores, você deve requisitar o código de ativação de seu acesso ao banco de dados SQL, antes de poder usá-lo. Se você não conseguir conectar, assegure-se de ter feito essa requisição.',
'install_info_subscribe_may_fail' => ' Um pedido para assinar o seu e-mail para os anúncios de LCM foi enviada. Às vezes, a solicitações automatizadas podem não funcionar. Se você não receber uma confirmação por e-mail dentro de 24 horas a seguir, por favor, assine em nosso site.',
'install_info_subscribe_to_news_list' => ' Inscrever-se acima do e-mail para receber a annoucements LCM? Se sim, você receberá por e-mail informações sobre novos lançamentos de software estável e notificações de segurança importantes. Esses e-mails são enviados muito raramente (uma vez a cada 1-2 meses) e nunca serão usados para outros fins, como a publicidade.',
'install_input_database_name' => ' Nome:',
'install_input_getnews' => ' Assinatura do boletim anúncios:',
'install_select_database' => 'Selecione o banco de dados que seu servidor atribuiu a você',
'install_select_language' => 'Selecione a linguagem e aperte no botão proceder para iniciar o processo de instalação.',
'install_step_five' => 'Quinto passo:',
'install_step_four' => 'Quarto passo:',
'install_step_last' => 'Último passo:',
'install_step_one' => 'Primeiro passo:',
'install_step_three' => 'Terceiro passo:',
'install_step_two' => 'Segundo passo:',
'install_title_admin_account' => 'Informação pessoal para acesso do administrador',
'install_title_creating_database' => 'Criando as tabelas do banco de dados',
'install_title_installation_start' => 'Instalação do software de gerenciamento de processo judicial...',
'install_title_select_database' => 'Escolhendo seu banco de dados',
'install_title_sql_connection' => 'Sua conexão com a base de dados SQL',
'install_warning_no_admins_exist' => ' Você deve criar uma conta ou você não será capaz de login no sistema.',
'install_warning_no_databases_1' => 'o instalador não conseguiu ler os nomes disponíveis no banco de dados.',
'install_warning_no_databases_2' => 'Ou há outro banco de dados disponível, ou o mecanismo de visualização dos bancos de dados disponíveis esta desabilitado por motivos de segurança (coisa comum na maioria dos servidores).',
'install_warning_no_databases_3' => 'No caso da segunda alternativa ser verdadeira, é possível que o banco de dados nomeado após o seu login possa ser utilizado:',
'install_warning_update_impossible' => '<b>ALERTA!</b> Erro ao tentar atualizar o banco de dados da versão @old_version@ para versão @version@, pode ser um problema nas permissões do banco de dados. Por favor contate seu administrador. Uma lista completa dos problemas é disponibilizada abaixo.',


// K
'keywords_button_kw_new' => '  Criar um item novo campo',
'keywords_button_kwg_edit' =>'  Modificar campo grupo',
'keywords_button_kwg_new' => '  Criar um grupo novo campo',
'keywords_button_subkwg_new' => ' Criar um novo sub-grupo',
'keywords_cache_refreshed' => 'Palavras-chaves de atualização de cache',
'keywords_info_kw_ac_author'=> ' Pode autores seleccionar este item de campo? (Caso contrário, será oculto)',
'keywords_info_kw_hidden' =>' escondido',
'keywords_info_kwg_ac_author' => '  Os usuários podem escolher entre este grupo de campo? (Caso contrário, será oculto)',
'keywords_info_kwg_hidden'=> '  (escondido)',
'keywords_info_maintenance'=>'  É possível que, entre as atualizações LCM, um problema pode ter ocorrido durante a atualização de informações do sistema. Para forçar uma atualização, clique no botão abaixo validação. Isso não afetará a sua configuração existente.',
'eywords_info_quantity' => '  O usuário pode selecionar a quantidade @ @ deste grupo em uma determinada situação (processo, andamento, etc.) ',
'keywords_input_description' => '  Descrição: ',
'keywords_input_for_group' => '  No campo grupo:',
'keywords_input_name' => '  Pasta:',
'keywords_input_policy' => '  Política:',
'keywords_input_policy_mandatory' =>'  Obrigatória',
'keywords_input_policy_optional' =>'  Opcional',
'keywords_input_policy_recommended'=> '  recomendado ',
'ywords_input_suggest' =>'  escolha padrão: ',
'keywords_input_title' =>'  Título:',
'keywords_input_type' => '  se aplica a:',
'keywords_input_type_case' => '  Processos',
'keywords_input_type_adverso' => '  Adversos',
'keywords_input_type_adverso_cliente' => ' adversos e empresas',
'keywords_input_type_contact' =>'  Contatos ',
'keywords_input_type_followup' => '  Siga-ups',
'keywords_input_type_cliente' =>'  Organizações',
'keywords_input_type_stage' => '  Judiciário',
'keywords_input_type_system' => '  System',
'keywords_option_quantity_many' => '  muitos itens',
'keywords_option_quantity_one'=> '  um item',
'keywords_tab_contact' => '  Tipos de contato',
'keywords_tab_maintenance' => ' Manutenção',
'keywords_tab_system' => '  Campos do sistema',
'keywords_tab_user' => '  Campo dos processos',
'keywords_warning_kw_code_exists' => '  O código já está sendo usado por outro item de campo neste grupo.',
'keywords_warning_kwg_code_exists' => '  O código já está sendo usado por outro grupo de campo.',
'kw__crimresults_none_title' => '  Nenhum resultado',
'kw__crimresults_res001_title'=>'  Sentença',
'kw__crimresults_res002_title' => '  Decisão',
'kw__crimresults_res003_title'=>'  Acordo',
'kw__crimresults_res004_title'=>'  Despedimento',
'kw__crimresults_res005_title'=>'  Cessação',
'kw__crimresults_res006_title'=>'  Parado',
'kw__crimresults_res007_title' => '  Portaria',
'kw__crimresults_res008_title' => ' Outros',
'kw__exptypes__exptypes01_title' =>' Tipo 1',
'kw__exptypes__exptypes02_title' =>' Tipo 2',
'kw__exptypes__exptypes_other_title' =>' Outros',
'kw__institutions_001_title' =>' TJPE',
'kw__institutions_002_title' =>' TRF 5ª',
'kw__institutions_003_title' =>' TRT 6ª',
'kw__refnumbers_courtarchive_title' => ' Arquivo Tribunal de Justiça',
'kw__refnumbers_filenum_title'=> ' Processo',
'kw__refnumbers_initialrefnum_title' => ' Referência inicial',
'kw_appointments_court_session_title' => ' Audiência',
'kw_appointments_meeting' => 'Reunião',
'kw_appointments_' => ' modo Geral',
'kw_appointments_phone_conversation' => 'Contato telefônico',
'kw_appointments_court_session' => ' Audiência',
'kw_appointments_appointments04' => 'Prazo',
'kw_appointments_appointments05' => 'Compromisso',
'kw_appointments_meeting_title' => ' Reunião',
'kw_appointments_phone_conversation_title' => ' Contato telefônico',
'kw_civilstatus_divorced_title' => ' Divorciado',
'kw_civilstatus_married_title' => ' Casados',
'kw_civilstatus_single_title' =>' Solteiro',
'kw_civilstatus_unknown_title' =>' Desconhecido',
'kw_civilstatus_widowed_title' =>' Viúvo',
'kw_conclusion_cessation_title' =>' Com resolução do mérioto',
'kw_conclusion_guilty_title' => ' Pocedente',
'kw_conclusion_none_title' =>' Sem resolução do mérioto',
'kw_conclusion_notguilty_title' => ' Não pocedente',
'kw_conclusion_reinvestigation_title' =>' Re-Distribuição',
'kw_contacts_addressmain_title' => ' Endereço',
'kw_contacts_emailalternate_title' =>' E-mail (alternativo)',
'kw_contacts_emailmain_title' => 'E-mail',
'kw_contacts_phonehome_title' => 'Fones',
'kw_contacts_phonemobile_title' => 'Fone (celular)',
'kw_contacts_phoneoffice_title' => 'Fone (cliente)',
'kw_followups__title' =>' - ',
'kw_followups_other_title' =>' - ',
'kw_followups_assignment_title'=> 'ATRIBUIÇÃO',
'kw_followups_conclusion_title'=> 'ENCERRADO',
'kw_followups_consultation_title'=> 'CONSULTA',
'kw_followups_correspondance_title'=> 'NOTIFICAÇÃO',
'kw_followups_delay_title' => 'ATRASO',
'kw_followups_deletion_title' => ' DELETAR',
'kw_followups_followups07_title' => ' VEÍCULO LOCALIZADO',
'kw_followups_merge_title' => ' EXTINTO',
'kw_followups_opening_title' => ' ABERTURA',
'kw_followups_other_title' => 'OUTRO',
'kw_followups_reopening_title' => ' REABERTURA',
'kw_followups_resumption_title' => ' REINÍCIO',
'kw_followups_stage_change_title' => ' ALTERAÇÃO DE FASE',
'kw_followups_suspension_title' =>'SUSPENSÃO',
'kw_followups_travel_title' =>'VIAGEM',
'kw_followups_unassignment_title' =>'DESPACHO',
'kw_income_average_title' => ' Média',
'kw_income_high_title' =>' Acima da média',
'kw_income_low_title' => ' Abaixo da média',
'kw_income_unknown_title' => ' Desconhecido',
'kw_sentence_community_title' => ' Trabalhos comunitários (dias)',
'kw_sentence_fine_title' =>' Multa (@currency@)',
'kw_sentence_none_title' =>' Restrintintiva de Direitos',
'kw_sentence_prison_title' => ' Privativa de Liberdade (meses)',
'kw_sentence_probation_title' => ' Suspensão (meses)',
'kw_stage_appeal_title'=> ' Primeiro Recurso',
'kw_stage_investigation_title'=> ' Em andamento',
'kw_stage_pre-trial_title' => ' Sentença',
'kw_stage_second_appeal_title' =>' Segundo Recurso',
'kw_stage_trial_title' => ' Acórdão',
'kwg__crimresults_title' => ' Resultados do Processo',
'kwg__exptypes_title' =>' Pedido Interno',
'kwg__institutions_title' =>' Tribunal',
'kwg__refnumbers_title' =>' Número de referência',
'kwg_appointments_title' =>' Compromissos',
'kwg_civilstatus_title' => ' Status Civil',
'kwg_conclusion_title' =>' Conclusão do Processo',
'kwg_contacts_title' =>' Campos de contato',
'kwg_followups_title' => ' Campos de Acompanhamento',
'kwg_income_title' => ' Renda',
'kwg_sentence_title' => ' Sentença da Corte',
'kwg_stage_title' => ' Fase do Processo',
'kw_followups_followups08_title' => 'CONCLUSO',
'kw_followups_followups09_title' => 'AUDIÊNCIA',
'kw_followups_followups10_title' => 'ACORDO',
'kw_followups_followups11_title' => 'AGUARDANDO DISTRIBUIÇÃO',
'kw_followups_followups12_title' => 'AGRAVO DE INSTRUMENTO',
'kw_followups_followups13_title' => 'AGUARDANDO SENTENÇA',
'kw_followups_followups14_title' => 'AGUARDANDO TRANSITO',
'kw_followups_followups15_title' => 'ALVARÁ',
'kw_followups_followups16_title' => 'APELAÇÃO',
'kw_followups_followups17_title' => 'APENSO REVISIONAL',
'kw_followups_followups18_title' => 'AUDIÊNCIA DE CONCILIAÇÃO',
'kw_followups_followups19_title' => 'AUDIÊNCIA DE INSTRUÇÃO',
'kw_followups_followups20_title' => 'CONTESTAÇÃO',
'kw_followups_followups21_title' => 'CONTESTAÇÃO',
'kw_followups_followups22_title' => 'DEPÓSITO',
'kw_followups_followups23_title' => 'DESISTÊNCIA',
'kw_followups_followups24_title' => 'DISTRIBUIÇÃO',
'kw_followups_followups25_title' => 'EDITAL DE CITAÇÃO',
'kw_followups_followups26_title' => 'EMBARGOS DE DECLARAÇÃO',
'kw_followups_followups27_title' => 'EMBARGOS DE TERCEIROS',
'kw_followups_followups28_title' => 'EMENDA INICIAL',
'kw_followups_followups29_title' => 'EXCEÇÃO',
'kw_followups_followups30_title' => 'EXECUÇÃO',
'kw_followups_followups31_title' => 'LIMINAR DEFERIDA',
'kw_followups_followups32_title' => 'LIMINAR INDEFERIDA',
'kw_followups_followups33_title' => 'MANDADO EXPEDIDO',
'kw_followups_followups34_title' => 'MANDADO DE CITAÇÃO',
'kw_followups_followups35_title' => 'MANDADO DEVOLVIDO',
'kw_followups_followups36_title' => 'NOTIFICAÇÃO',
'kw_followups_followups37_title' => 'OFÍCIO',
'kw_followups_followups38_title' => 'PENHORA',
'kw_followups_followups39_title' => 'PROCESSO NÃO LOCALIZADO',
'kw_followups_followups40_title' => 'RECONVENÇÃO',
'kw_followups_followups41_title' => 'SENTENÇA IMPROCEDENTE',
'kw_followups_followups42_title' => 'SENTENÇA PROCEDENTE',
'kw_followups_followups43_title' => 'SENTENÇA SEM RESOLUÇÃO DO MÉRITO',
'kw_followups_followups44_title' => 'SUSPENSÃO',
'kw_followups_followups45_title' => 'VEÍCULO APREENDIDO',
'kw_followups_followups46_title' => 'PUBLICAÇÃO',
'kw_followups_followups47_title' => 'JUNTADA',
'kw_followups_followups48_title' => 'PETIÇÃO',
'kw_followups_followups49_title' => 'PROTOCOLO',
'kw_followups_followups50_title' => 'RÉPLICA',
'kw_followups_followups51_title' => 'EMBARGOS À EXECUÇÃO',
'kw_followups_followups52_title' => 'EXCEÇÃO DE PRÉ-EXECUTIVIDADE',
'kw_followups_followups53_title' => 'ACÓRDÃO',
'kw_followups_followups54_title' => 'REMESSA',
'kw_followups_followups55_title' => 'EXPEDIR MANDADO',
'kw_followups_followups56_title' => 'VEÍCULO DEVOLVIDO',
'kw_followups_followups57_title' => 'CARTA PRECATÓRIA',
'kw_followups_followups58_title' => 'EXECUÇÃO DE HONORÁRIOS',
'kw_followups_followups59_title' => 'EXECUÇÃO DE SENTENÇA',
'kw_followups_followups60_title' => 'RECURSO INOMINADO',
'kw_followups_followups61_title' => 'AGUARDANDO PROTESTO',
'kw_followups_followups62_title' => 'DILIGÊNCIA - ENVIADA',
'kw_followups_followups63_title' => 'SENTENÇA CONSOLIDATÓRIA',
'kw_followups_followups64_title' => 'SENTENÇA HOMOLOGATÓRIA',
'kw_followups_followups65_title' => 'DILIGÊNCIA - RETORNO',
'kw_followups_followups66_title' => 'DESENTRANHAMENTO DO MANDADO',
'kw_followups_followups67_title' => 'AÇÃO NÃO DISTRIBUÍDA',
'kw_followups_followups68_title' => 'INICIAL ELABORADA',
'kw_followups_followups69_title' => 'SENTENÇA PARCIALMENTE PROCEDENTE',
'kw_followups_followups70_title' => 'ARQUIVADO',
'kw_followups_followups71_title' => 'CUMPRIMENTO DE SENTENÇA',
'kw_followups_followups72_title' => 'CONTRARRAZÕES',
'kw_followups_followups73_title' => 'TRÂNSITO EM JULGADO',
'kw_followups_followups74_title' => 'INICIAL RECEBIDA',
'kw_followups_followups75_title' => 'RECLAMAÇÃO',
'kw_followups_followups76_title' => 'VENDA VEÍCULO',
'kw_followups_followups77_title' => 'CUSTAS A PAGAR',
'kw_followups_followups78_title' => 'DECISÃO STJ',
'kw_followups_followups79_title' => 'SUBSÍDIOS',
'kw_followups_followups80_title' => 'ALVARÁ LEVANTADO',
'kw_followups_followups81_title' => 'CUSTAS PAGAS',

// L
'listnav_link_gotopage' => ' Ir para página:',
'listnav_link_next' => ' Próximo',
'listnav_link_previous' => ' Anterior',
'listnav_link_show_all' => ' Todos',
'login_access_denied' => 'Acesso negado:',
'login_identifier_unknown' => 'A identificação "@login@" é desconhecido.',
'login_info_login' => 'identifique-se para se conectar ao site',
'login_link_reload_page' => 'Atualizar esta página',
'login_login' => 'Login:',
'login_other_identifier' => 'conectar com outra identificação',
'login_password' => 'Senha:',
'login_password_confirm' => 'Confirmar a senha',
'login_password_fclienteotten' => 'Esqueceu sua senha?',
'login_password_incorrect' => 'Login ou senha incorretos.',
'login_register' => 'Registrar-se no site',
'login_remain_logged_on' => 'Lembrar da autenticação por alguns dias',
'login_this_way' => 'Você é registrado... este caminho...',
'login_title_login' => 'Login',
'login_warning_already_exists' => 'Este usuário já existe.',
'login_warning_cookie' => ' Seu navegador não aceitar o cookie que é necessário para login.',
'login_warning_password_change_failed' => ' Falha ao alterar o nome de usuário:',
'login_warning_password_dont_match' => ' As senhas não coincidem.',
'login_warning_too_short' => 'O nome do usuário deve ter pelo menos 3 letras.',


// M
'menu_admin' => 'Administração',
'menu_admin_archives' => 'Arquivos',
'menu_admin_archives_tooltip' => ' Painel Administrativo para ferramentas de arquivo do sistema.',
'menu_admin_filters' => 'Filtros',
'menu_admin_keywords' => '<MODIF>Palavras Chave',
'menu_admin_keywords_tooltip' => ' Painel Administrativo para adicionar ou modificar os campos disponíveis no sistema.',
'menu_admin_reports' => 'Relatórios',
'menu_admin_reports_tooltip' => ' Painel Administrativo para criar e gerar relatórios de actividade.',
'menu_admin_siteconf' => 'Configuração do Sistema',
'menu_admin_siteconf_tooltip' => ' Painel Administrativo para adaptar o sistema para os hábitos de trabalho de seu cliente.',
'menu_agenda' => ' Agenda',
'menu_agenda_pending' => 'Pendência na agenda',
'menu_calendar' => 'Calendário',
'menu_fontsize' => ' Tamanho da fonte',
'menu_main' => 'Menu Principal',
'menu_main_authors' => 'Usuários',
'menu_main_authors_tooltip' => ' Lista de todos os usuários cadastrados no sistema.',
'menu_main_cases' => 'Processos',
'menu_main_cases_tooltip' => ' Lista dos processos que está a trabalhar.',
'menu_main_adversos' => 'Adversos',
'menu_main_adversos_tooltip' => ' Lista de todos os adversos cadastrados no sistema.',
'menu_main_expenses' => ' Despesas',
'menu_main_expenses_tooltip' => ' Lista de despesas, como solicitações para cobrir as custas relacionadas a um processo.',
'menu_main_inicio' => 'Início',
'menu_main_andamentos' => 'Andamentos',
'menu_main_clientes' => 'Clientes',
'menu_main_clientes_tooltip' => ' Lista de todas as empresas (pessoas jurídicas) cadastrados no sistema.',
'menu_profile' => 'Perfil',
'menu_profile_logout' => 'Sair',
'menu_profile_logout_tooltip' => ' Sair do sistema.',
'menu_profile_preferences' => 'Configuração',
'menu_search' => 'Buscar',

// N
'new_followup' => 'Novo andamento',

// O
'cliente_button_add_rep' => ' Adicionar um representante',
'cliente_button_edit' => ' Edite as informações da cliente',
'cliente_button_new' => ' Registre um novo cliente',
'cliente_button_new_for_case' => ' Registrar um novo cliente e anexar a este processo',
'cliente_info_created_attached' => ' O cliente foi registrado e vinculado ao processo:',
'cliente_info_delete_adverso' => ' Excluir da relação cliente-adverso.',
'cliente_input_court_reg' => ' CNPJ:',
'cliente_input_id' => ' Cliente ID:',
'cliente_input_name' => 'Nome:',
'cliente_input_notes' => ' Notas:',
'cliente_input_stat_number' => ' Diretor / Preposto:',
'cliente_input_tax_number' => ' Atividade:',
'cliente_subtitle_attachments' => ' Anexos',
'cliente_subtitle_cases' => ' Processos que envolvem esta cliente',
'cliente_subtitle_representatives' => 'Representantes da Cliente',
'cliente_subtitle_view_general' => 'Informação Geral',

// P
'pass_back_to_site' => 'Volta a entrada do site',
'pass_close_this_window' => 'Fechar',
'pass_enter_new_pass' => '<MODIF>Por favor escolha sua nova senha',
'pass_info_automated_msg' => '(Esta é uma mensagem automâtica)',
'pass_info_enter_email' => 'Coloque seu e-mail com seu registro anterior. Você receberá em seu e-mail a forma de obter novamente seu acesso.',
'pass_info_here_info' => 'Aqui estão as informações para ter acesso ao site: "@site_name@" (@site_address@):',
'pass_info_identifier_mail' => 'Sua nova identificação esta sendo enviada a seu e-mail agora mesmo.',
'pass_info_moderated' => '<MODIF> Novos registros requerem a autorização pelo administrador do sistema. Você receberá uma confirmação em seu e-mail o mais rápido possível.',
'pass_info_pass_updated' => 'Sua nova senha foi gravada.',
'pass_info_password_by_mail' => 'Sua senha será enviada para seu e-mail.',
'pass_info_receive_mail' => 'Você receberá em seu e-mail a forma de obter novamente seu acesso.',
'pass_info_remind_username' => 'Lembre-se: Sua identificação (login) é "@login@".',
'pass_info_why_register' => 'Para usar o sistema de gerenciamento de processos (Torres - Sistemas), você precisa criar uma conta pessoal. Você pode registrar no site preenchendo no campo abaixo seu e-mail.',
'pass_mail_cookie1' => 'Para obter acesso ao site:',
'pass_mail_cookie2' => 'Por favor vá ao seguinte endereço:',
'pass_mail_cookie3' => 'Você pode entrar uma nova senha e se reconectar ao site.',
'pass_more_than_5_or_random' => '(Mais de 5 letras. Se deixar em branco, uma senha aleatória será gerada e enviada para seu e-mail.)',
'pass_title_fclienteotten_password' => 'Senha esquecida',
'pass_title_new_pass' => 'Nova Senha',
'pass_title_personal_identifier' => 'Identificação Pessoal',
'pass_title_register' => 'Registrar-se no site',
'pass_warning_already_registered' => 'Você já é registrado. se você perdeu sua senha, click em "senha esquecida" na página de entrada.',
'pass_warning_incorrect' => 'Senha incorreta.',
'pass_warning_invalid_email' => '<b>Erro:</b> O e-mail <tt>@user_email@</tt> não é válido!',
'pass_warning_mail_failure' => 'Problema no correio: A identificação não pode ser enviada. Por favor contate o administrador pelo e-mail: (@email_admin@).',
'pass_warning_not_registered' => '<b>Erro:</b> O endereço <tt>@user_email@</tt> não está registrado no site.',
'pass_warning_too_short' => 'A senha deve conter mais de 5 letras.',
'pass_warning_unknown_cookie' => '<b>Erro:</b> Este código é desconhecido.',
'person_info_years_old' => ' @years@ anos',
'person_input_address' => 'Endereço:',
'person_input_citizen_number' => 'Número de RG:',
'person_input_cpfcnpj' => 'Número do CPF/CNPJ:',
'person_input_civil_status' => 'Condição Civil:',
'person_input_date_birth' => ' Data de nascimento:',
'person_input_gender' => 'Gênero:',
'person_input_cpfcnpj' => 'CPF/CNPJ:',
'person_input_gender_female' => 'Feminino',
'person_input_gender_male' => 'Masculino',
'person_input_gender_unknown' => ' n/a',
'person_input_income' => 'Income:',
'person_input_name' => ' Nome:',
'person_input_name_all' => 'Nome Completo:',
'person_input_name_first' => 'Nome:',
'person_input_name_last' => 'Sobre nome:',
'person_input_name_middle' => 'Segundo nome:',

// R
'rep_button_edit' => 'Editar detalhe dos relatórios',
'rep_button_exportcsv' => ' Exportar o relatório',
'rep_button_goback' => ' Volte para o relatório de detalhes',
'rep_button_new' => 'Novo relatório',
'rep_button_nokw_hide' => ' Ocultar coluna de itens sem uma palavra-chave',
'rep_button_nokw_show' => ' Mostrar a coluna de itens sem uma palavra-chave',
'rep_button_run' => ' Gerar o relatório',
'rep_filter_date_eq' =>' =',
'rep_filter_date_ge' => '=',
'rep_filter_date_gt' => '>',
'rep_filter_date_in' => ' em',
'rep_filter_date_le' => '=',
'rep_filter_date_lt' => '<',
'rep_filter_none' => ' nenhum',
'rep_filter_num_eq' =>' =',
'rep_filter_num_ge' => '=',
'rep_filter_num_gt' => '>',
'rep_filter_num_le' => '=',
'rep_filter_num_lt' => '<',
'rep_filter_text_eq' =>' =',
'rep_filter_text_neq' => ' !=',
'rep_info_select_source_first' => ' Para aplicar os filtros, você deve primeiro selecionar o conteúdo que será utilizado para a linha do relatório e colunas.',
'rep_info_source_keyword' => ' Campo Personalizado:',
'rep_info_source_table' => ' Tabela:',
'rep_info_table_lcm_author' => ' Usuário',
'rep_info_table_lcm_case' => ' Processo',
'rep_info_table_lcm_adverso' => ' Adverso',
'rep_info_table_lcm_followup' => ' Acompanhamento',
'rep_info_table_lcm_cliente' => ' Cliente',
'rep_info_table_lcm_stage' => ' Processo fase ',
'rep_info_table_lcm_app' => ' Agenda ',
'rep_info_table_lcm_system' => ' Sistema',
'rep_input_description' => ' Descrição:',
'rep_input_field_count' => ' Contagem',
'rep_input_filter_add' => ' Adicione um filtro com base nesse campo:',
'rep_input_id' => 'Relatório ID:',
'rep_input_item_add' => ' Adicionar um campo:',
'rep_input_notes' => ' Notas:',
'rep_input_title' => 'Título:',
'rep_subtitle_column' => ' Mais informações',
'rep_subtitle_filters' => ' Filtros de relatório',
'rep_subtitle_line' => ' RELATÓRIO DE INFORMAÇÕES',
'rep_warning_atleastlineinfo' => ' Você deve selecionar pelo menos, a fonte para a informação da linha de relatório.',

// S
'save' => 'Salvar',
'sendmail_title' => 'Título',
'sendmail_adverso' => 'Adverso',
'sendmail_partes' => 'Partes',
'sendmail_vara' => 'Vara',
'sendmail_comarca' => 'Comarca',
'sendmail_acao' => 'Ação',
'sendmail_pasta' => 'Pasta',
'sendmail_compromisso' => 'Compromisso',
'sendmail_descricao' => 'Descrição',
'sendmail_processo' => 'N° do Processo',
'sendmail_data' => 'Data do compromisso',
'siteconf_info_admin_email' => 'E-mail do contato administrativo para relatar problemas.',
'siteconf_info_email_agenda' => 'E-mail para envio da agenda.',
'siteconf_info_available_languages' => 'Se você tiver adicionado um novo arquivo de língua ao LCM ou atualizado o software e nem todos as liguas estiverem disponíveis, clique em "salvar" para atualizar a lista de linguagens disponíveis.',
'siteconf_info_case_fields' => 'Você pode customizar o tipo de informação guardada em cada processo. Isso depende do tipo de atividade de seu cliente.',
'siteconf_info_changes_made' => ' As configurações foram actualizadas:',
'siteconf_info_adverso_fields' => 'Você pode customizar as informações dos adverso e dos usuários. Por favor note que algumas configurações, como o número do RG, é extremamente desaconselhavel e deve ser mantida de fora.',
'siteconf_info_currency' => 'Moeda para qualquer tipo de informação financeira, inseridas no sistema (como faturamento, se ativado).',
'siteconf_info_default_lang' => 'Idioma a ser usado se uma língua não pode ser detectado ou escolhidos (como para novos usuários).',
'siteconf_info_followups_fields' => 'Você pode personalizar o tipo de informação para armazenar em cada seguimento. Isso depende principalmente sobre as actividades do seu cliente.',
'siteconf_info_hide_emails' => 'Esconder os e-mails dos usuários',
'siteconf_info_languages_refreshed' => ' A lista de traduções disponíveis foi atualizado.',
'siteconf_info_name_format_1' => ' John J. Doe',
'siteconf_info_name_format_10' => ' Doe, John J.',
'siteconf_info_now_and_before' => ' agora está definido para “@now@”, já era “@before@”.',
'siteconf_info_self_registration' => 'Os usuários podem criar-se uma nova conta (por exemplo, registar-se) sobre o site?',
'siteconf_info_site_desc' => 'Muitas vezes, apresentado sob o nome do site, exceto nos relatórios.',
'siteconf_info_site_name' => 'Isso será mostrado quando o usuário efetua login, em relatórios gerados, etc.',
'siteconf_input_access_read_choice' => 'Por padrão, quem pode consultar as informações relativas a um novo processo?',
'siteconf_input_access_read_choice_private' => ' Somente usuários atribuídos a um processo e os administradores podem consultar a informação (para privacidade).',
'siteconf_input_access_read_choice_public' => ' Qualquer usuário pode consultar as informações relacionadas aos processos de outros usuários, mesmo que eles não são atribuídos sobre o processo (para a cooperação e transparência).',
'siteconf_input_access_read_global' => 'Impor a definição acima como uma política local?',
'siteconf_input_access_read_global_no' => ' Não, qualquer usuário atribuído no processo (e com "editar" direitos) pode modificar o acesso de leitura.',
'siteconf_input_access_read_global_yes' => 'Sim, somente os administradores podem modificar o acesso a ler.',
'siteconf_input_access_write_choice' => 'Por padrão, o que pode contribuir com informações para um novo processo?',
'siteconf_input_access_write_choice_private' => ' Somente usuários atribuídos a um processo e os administradores podem contribuir para isso.',
'siteconf_input_access_write_choice_public' => ' Qualquer usuário pode contribuir com informações para os processos de outros usuários, mesmo que eles não são atribuídos sobre o processo.',
'siteconf_input_access_write_global' => 'Impor a definição acima como uma política local?',
'siteconf_input_access_write_global_no' => ' Não, qualquer usuário atribuído sobre o processo (e com "editar" direitos) pode modificar o acesso de gravação.',
'siteconf_input_access_write_global_yes' => 'Sim, somente os administradores podem modificar o acesso de gravação.',
'siteconf_input_admin_email' => 'E-mail da administração do site:',
'siteconf_input_email_agenda' => 'E-mail para avisos da agenda:',
'siteconf_input_available_languages' => 'Atualizar a lista de idiomas disponíveis:',
'siteconf_input_case_allow_modif' => 'Permitir a informação do processo a ser modificado, uma vez que são criados?',
'siteconf_input_case_new_showcliente' => ' Mostrar o &ldquo;encontrar/criar um cliente&rdquo; forma ao criar um novo processo?',
'siteconf_input_citizen_number' => 'Número do RG (apenas para adversos)',
'siteconf_input_cpfcnpj' => 'Número do CPF/CNPJ (apenas para adversos)',
'siteconf_input_adverso_income' => ' Renda',
'siteconf_input_court_archive' => 'Nº do Processo no Fôrum',
'siteconf_input_currency' => 'Moeda:',
'siteconf_input_default_lang' => 'Linguagem padrão:',
'siteconf_input_fu_allow_modif' => 'Permitir que as informações de andamento a ser modificado, uma vez que são criados?',
'siteconf_input_name_format' => ' Nome do formato:',
'siteconf_input_name_middle' => 'Nome do meio ou inicial',
'siteconf_input_selfreg_moderated' => 'Sim, mas um administrador tem que aprovar (moderado) o pedido.',
'siteconf_input_selfreg_no' => 'Não',
'siteconf_input_selfreg_yes' => 'Sim, sem moderador.',
'siteconf_input_site_address' => 'Endereço da Internet ou localização na intranet:',
'siteconf_input_site_desc' => 'Descrição do Site:',
'siteconf_input_site_name' => 'Nome do Site:',
'siteconf_subtitle_case_fields' => 'Processos',
'siteconf_subtitle_adverso_fields' => 'Adversos e usuários',
'siteconf_subtitle_collab_work' => ' O trabalho colaborativo',
'siteconf_subtitle_followup_fields' => 'Andamentos',
'siteconf_subtitle_info_sharing' => ' A partilha de informação',
'siteconf_subtitle_refresh_lang' => ' Atualizar a lista de idiomas disponíveis',
'siteconf_subtitle_regional' => 'Configurações Regionais',
'siteconf_subtitle_self_registration' => 'Auto-registro para usuários',
'siteconf_subtitle_site_contacts' => ' Site localização e contactos',
'siteconf_subtitle_site_agenda' => ' Site e-mails para agenda',
'siteconf_subtitle_site_identification' => ' Site identificação',
'siteconf_tab_collab_work' => 'Trabalho colaborativo',
'siteconf_tab_general' => 'Informação Geral',
'siteconf_tab_policy' => 'Política do Escritório',
'siteconf_tab_regional' => 'Configurações Regionais',
'siteconf_warning' => '<b>Atenção!</b> As configurações e modificações desta página influenciam no funcionamento do site.',
'siteconf_warning_currency' => '<b>Cuidado!</b> Se você modificar a moeda, as informações atuais <strong>não</strong> serão convertidas.',
'show_page_subtitle_info' => 'Informações',
'show_page_subtitle_info_followup' => 'Acompanhamento de informação',

// T
'time_info_before_start' => 'antes da hora de início.',
'time_info_short_day' => ' d',
'time_info_short_hour' => ' h',
'time_info_short_min' => ' m',
'time_input_date_creation' => ' Data de criação:',
'time_input_date_end' => ' Terminar:',
'time_input_date_start' => ' Entrada:',
'time_input_date_start_agenda' => 'Data',
'time_input_app_type' => ' / Tipo:',
'title_agenda_geral' => ' Relatório geral da agenda',
'time_input_date_start_evento' => ' Data do evento:',
'time_input_date_updated' => ' Atualizado:',
'time_input_length' => ' Tempo:',
'time_input_time_at' => ' hs',
'time_warning_invalid_format' => ' The time lenght is not valid.',
'title_agenda_list' => ' Agenda',
'title_app_edit' => ' Editar agendamento',
'title_app_new' => ' Novo agendamento',
'title_app_view' => ' Detalhes da Atividade:',
'title_archives' => ' Arquivo',
'title_author_edit' => ' Editar usuários:',
'title_author_list' => ' Lista de usuários',
'title_author_new' => ' Novo usuário:',
'title_author_view' => ' Detalhes do Usuário:',
'title_author_view_app' => ' Agenda de',
'title_authorconf' => 'Minhas preferencias',
'title_calendar_view' => ' Agenda',
'title_case_add_author' => ' Adicionar um usuário para o processo',
'title_case_add_adverso' => ' Adicione um adverso para o processo',
'title_case_add_cliente' => ' Adicionar um cliente para o processo',
'title_case_details' => 'Detalhes do processo:',
'title_case_edit' => 'Editar detalhes do processo',
'title_case_edit_ac' => ' Editar direitos de acesso',
'title_case_new' => 'Novo processo',
'title_adverso_edit' => 'Editar adverso:',
'title_adverso_list' => ' Lista de adversos',
'title_adverso_new' => 'Novo adverso',
'title_adverso_view' => 'Adverso:',
'title_error' => 'Erro',
'title_expense_comment' => ' Solicitação de atualização',
'title_expense_new' => ' Novo pedido interno',
'title_expense_view' => ' Detalhes do Pedido',
'title_expenses' => ' Despesas',
'title_fu_change_stage' => ' Mudança de fase',
'title_fu_change_status' => ' Caso de mudança de status',
'title_fu_edit' => ' Editar seguimento',
'title_fu_new' => ' Novo andamento',
'title_fu_view' => ' Mais detalhes',
'title_keyword_edit' => ' Editar item de campo',
'title_keyword_new' => ' Novo item de campo',
'title_kwg_edit' => ' Editar grupo campo',
'title_kwg_new' => ' Novo grupo de domínio',
'title_my_cases' => ' Acompanhamento Processual',
'title_cliente_edit' => ' Editar cliente:',
'title_cliente_list' => ' Lista dos clientes',
'title_cliente_new' => ' Nova cliente:',
'title_cliente_select_adverso' => ' @name_cliente@: Selecione os representantes...',
'title_cliente_view' => ' Cliente:',
'title_rep_edit' => ' Editar relatório:',
'title_rep_new' => ' Novo relatório',
'title_rep_run' => ' Relatório de resultado:',
'title_rep_view' => ' Os detalhes do relatório:',
'title_report_list' => ' Lista dos relatórios',
'title_site_configuration' => 'Configuração do Sistema',
'title_software' => 'Torres - Sistemas Jurídicos  -',
'title_software_description' => 'Sistema de acompanhamento processuaul',
'title_technical_message' => 'Mensagem técnica:',
'title_technical_problem' => 'Problema Técnico',
'title_upgrade_database' => ' Atualização de banco de dados',
'typo_column' => ':',


// W
'warning_already_installed' => 'Sistema já instalado.',
'warning_field_mandatory' => ' Campo obrigatório.',
'warning_field_mandatory_all' => ' Todos os campos são de preenchimento obrigatório.',
'warning_forbidden_area' => 'área esquecida',
'warning_forbidden_not_admin' => ' Acesso negado: você não tem o direito administrativo para aceder a esta secção.',
'warning_operation_failed' => 'A operação falhou',
'warning_panic_is_useful' => ' Um erro inesperado ocorreu, mas as informações fornecidas abaixo vai ajudar os desenvolvedores de software para corrigir o erro. Por favor, copie e cole a mensagem abaixo e enviá-lo por e-mail para fabio@direito2010.com.br',
'warning_sql_connection_failed' => 'Conexão com o servidor da base de dados SQL falhou.',
'warning_sql_query_failed' => 'Erro na base de dados SQL.',
'case_subtitle_stage' => 'Fase do processo'
);


// Formats time interval
function format_time_interval($time, $hours_only=false, $hours_only_format='%.2f') {
	$ret = array();
		if (! is_numeric($time))
			return '';

		if ($time == 0)
			return '0';

		if ($time < 0)
			return '-1'; // should never happen, right? :-)

		if ($hours_only) {
			$days = 0;
			$hours = $time / 3600;
			$minutes = 0;
		} else {
			$days = (int) ($time / 86400);
			$hours = (int) ( ($time % 86400) / 3600);
			$minutes = (int) ( ($time % 3600) / 60);
		}
	

	if ($days)
		$ret[] = $days . ($hours_only ? '' : '&nbsp;' . $andamentos['time_info_short_day']);

	if ($hours) {
		if ($hours_only) // limit hours to 2 decimals
			$ret[] = sprintf($hours_only_format, $hours)
				. ($hours_only ? '' : '&nbsp;' . $andamentos['time_info_short_hour']);
		else
			$ret[] = $hours . ($hours_only ? '' : '&nbsp;' . $andamentos['time_info_short_hour']);
	}

	if ($minutes) 
		$ret[] = $minutes . ($hours_only ? '' : '&nbsp;' . $andamentos['time_info_short_min']);

	return join(' ',$ret);
}

function format_time_interval_prefs($time) {
	global $prefs;

	$hours_only = $prefs['time_intervals_notation'] == 'hours_only';
	return format_time_interval($time, $hours_only);
}


$cod_fnal = array(
'agua branca'=>3,
'anadia'=>2,
'batalha'=>16,
'boca da mata'=>17,
'cacimbinhas'=>8,
'cajueiro'=>7,
'campo alegre'=>9,
'canapi'=>68,
'colonia leopoldina'=>11,
'feira grande'=>60,
'flexeiras'=>5,
'girau do ponciano'=>14,
'igaci'=>6,
'igreja nova'=>49,
'joaquim gomes'=>51,
'junqueiro'=>50,
'limoeiro de anadia'=>52,
'major izidoro'=>19,
'maravilha'=>22,
'maribondo'=>24,
'mata grande'=>20,
'matriz do camaragibe'=>25,
'messias'=>26,
'novo lino'=>28,
'olho dagua das flores'=>29,
'paripueira'=>33,
'passo de camaragibe'=>65,
'paulo jacinto'=>66,
'piacabucu'=>38,
'piranhas'=>37,
'porto de pedras'=>40,
'porto real do colegio'=>41,
'quebrangulo'=>42,
'santa luzia do norte'=>55,
'sao bras'=>67,
'sao jose da tapera'=>47,
'sao sebastiao'=>54,
'taquarana'=>63,
'teotonio vilela'=>56,
'traipu'=>57,
'atalaia'=>15,
'capela'=>18,
'cha preta'=>69,
'coruripe'=>12,
'delmiro gouveia'=>13,
'maragogi'=>21,
'marechal deodoro'=>23,
'murici'=>27,
'palmeira dos indios'=>30,
'pao de acucar'=>32,
'pilar'=>36,
'porto calvo'=>39,
'rio largo'=>43,
'santana do ipanema'=>53,
'sao jose da laje'=>45,
'sao luiz do quitunde'=>46,
'sao miguel dos campos'=>48,
'uniao dos palmares'=>58,
'vicosa'=>59,
'arapiraca'=>4,
'maceio'=>1,
'penedo'=>35 
);

function sanitizeString($string) {

    // matriz de entrada
    $what = array( 'ä','ã','à','á','â','ê','ë','è','é','ï','ì','í','ö','õ','ò','ó','ô','ü','ù','ú','û','À','Á','É','Í','Ó','Ú','ñ','Ñ','ç','Ç',' ','-','(',')',',',';',':','|','!','"','#','$','%','&','/','=','?','~','^','>','<','ª','º' );

    // matriz de saída
    $by   = array( 'a','a','a','a','a','e','e','e','e','i','i','i','o','o','o','o','o','u','u','u','u','A','A','E','I','O','U','n','n','c','C','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_','_' );

    // devolver a string
    return str_replace($what, $by, $string);
}


//Planilha de  fones dos localizadores
//$localizadores = array();
//$row = 1;
//$handle = fopen ("E://Publico/_BANCO_GMAC-BUSCA/LOCALIZADORES.csv","r");
//while (($data = fgetcsv($handle, 1000, ",")) !== FALSE){
//    $num = count ($data);
//    $row++;
//    for ($c=0; $c < $num; $c++) {
//        $lc = explode(";",$data[$c]);
//		$lc2 = array($lc[1],$lc[2],$lc[3],$lc[4],$lc[5],$lc[6],$lc[7],$lc[8]);
//    }
//	$localizadores[$lc[0]] = $lc2;
//}
//fclose ($handle);

//Planilha de fones das comarcas
//$fcomarcas = array();
//$rowc = 0;
//$fcoma = fopen ("E://Publico/_BANCO_GMAC-BUSCA/VARAS-COMARCAS.csv","r");
//while (($datac = fgetcsv($fcoma, 1000, ",")) !== FALSE){
//    $numc = count ($datac);
//    $rowc++;
//    for ($c=0; $c < $numc; $c++) {
//        $fc = explode(";",$datac[$c]);
//		$fc2 = array($fc[3]);
//    }
//	$cvara = tiraAcento(trim($fc[0]." - ".$fc[1]." - ".$fc[2]));
//	$fcomarcas[$cvara] = $fc2;
//}
//fclose ($fcoma);

function diasemana($data) {
	$ano =  substr("$data", 0, 4);
	$mes =  substr("$data", 5, -3);
	$dia =  substr("$data", 8, 9);

	return $diasemana = date("w", mktime(0,0,0,$mes,$dia,$ano));
	
}

$simnao = array(0=>"NAO",1=>"SIM");

function tiraAcento( $str ) {
	return strtr($str,'áàãâéêíóôõúüçÁÀÃÂÉÊÍÓÔÕÚÜÇ ','aaaaeeiooouucAAAAEEIOOOUUC_');
}

?>
